<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ironyx.Kernel" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Ironyx.ServiceIndex.Api">
      <HintPath>..\..\..\ironyx-service-index\src\Ironyx.ServiceIndex.Api\bin\Debug\net10.0\Ironyx.ServiceIndex.Api.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
